### ISSUE TITLE
Show error message and retry network call on connection loss

### ISSUE THREAD

**Issue by khalekuzzamancse** [khalekuzzamancse/JUST-Digital-Diary#55]
## Problems

- The destinations  with networks call  fails to fetch data from the REST API when there is no internet connection, and does not show any useful message to the user. 
- Moreover, when the internet connection is restored, the destination does not automatically retry the network call, and the user has to exit and re-enter the destination to get the data.

## Tasks

- [ ] Handle the network failure gracefully and show a meaningful error message to the user, such as `No internet connection,please check your settings and try again`
- [ ] Retry the network call when the internet connection is available, and update the view accordingly
- [ ] Present  a solution and explain why your solution is better
